[workspace]
authors = ["foolycoconut <smz.noisy@gmail.com>"]
channels = ["nvidia", "pytorch", "conda-forge"]
name = "ragtemp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-flash-attn = "pip install flash-attn --no-build-isolation"
qwen = "python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen3-30B-A3B-Instruct-2507-FP8 --tensor-parallel-size 2 --max-model-len 32768 --kv-cache-dtype fp8 --gpu-memory-utilization 0.90 --trust-remote_code --port 8002"

[dependencies]
python = "3.10.*"
setuptools = ">=80.9.0,<81"
numpy = ">=2.2.6,<3"
tqdm = ">=4.67.1,<5"
jinja2 = ">=3.1.6,<4"
transformers = ">=4.57.6,<5"
openai = ">=2.15.0,<3"
google-genai = ">=1.59.0,<2"

[pypi-dependencies]
torch = { version = "==2.6.0", index = "https://download.pytorch.org/whl/cu124" }
vllm = ">=0.8.5"
accelerate = ">=1.12.0, <2"
flashinfer-python = ">=0.6.1, <0.7"